iris-objs += iris_probe.o \
             iris_core.o \
             iris_vidc.o \
             iris_vb2.o \
             iris_hfi_common.o \
             iris_vdec.o \
             iris_state.o \
             iris_ctrls.o \
             iris_common.o \
             iris_hfi_1.o \
             iris_hfi_1_response.o \
             iris_hfi_2.o \
             iris_hfi_2_response.o \
             iris_hfi_2_packet.o \
             iris_hfi_queue.o \
             iris_buffer.o \
             iris_buffer_helpers.o \
             iris_power.o \
             iris_resources.o \
             iris_firmware.o \
             iris_utils.o \
             iris_vpu_buffer.o \
             iris_vpu_common.o \
             iris_vpu2.o \
             iris_vpu3.o \
             iris_platform_sm8550.o \
             iris_platform_sm8250.o \

obj-$(CONFIG_VIDEO_QCOM_IRIS) += iris.o
